apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          imagePullPolicy: IfNotPresent
          image: sekolahlinux/golang-http
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3              
          resources:
            requests:
              cpu: '256m'
              memory: '256Mi'
            limits:
              cpu: "512m"              
              memory: "512Mi"
